dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - name="openldap"
  - image="monogramm/docker-openldap:${VERSION}${VARIANT:+-$VARIANT}"
  - dir="images/${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" "$dir"

after_script:
  - docker images
  - docker run --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` --name "$name" -d "$image" "$dir"
  - docker ps
  - docker logs "$name"

notifications:
  email: false

env: # Environments
    - VERSION=1.1 VARIANT=debian
    - VERSION=1.2 VARIANT=debian
