os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master

before_install:
  - env | sort
  - dir="$(pwd)/images/${VERSION}${VARIANT:+-$VARIANT}"
  - IMAGE_NAME="monogramm/docker-openldap:${VERSION}${VARIANT:+-$VARIANT}-travis"

install:
  - cd "$dir"
  # Test containers build
  - travis_retry docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t "$image" .
  #- docker-compose -f docker-compose.test.yml build

before_script:
  - docker images

script:
  - cd "$dir"
  # Test containers run
  - travis_retry docker-compose -f docker-compose.test.yml up -d
  - docker-compose -f docker-compose.test.yml logs -f "sut"
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "openldap"
  - docker-compose -f docker-compose.test.yml ps "openldap" | grep "Up"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"
  # Test containers can be restarted
  - docker-compose -f docker-compose.test.yml restart
  - docker-compose -f docker-compose.test.yml logs -f "sut"
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "openldap"
  - docker-compose -f docker-compose.test.yml ps "openldap" | grep "Up"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"
  # Test containers can be dropped
  - docker-compose -f docker-compose.test.yml down
  - travis_retry docker-compose -f docker-compose.test.yml up -d
  - docker-compose -f docker-compose.test.yml logs -f "sut"
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "openldap"
  - docker-compose -f docker-compose.test.yml ps "openldap" | grep "Up"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"

notifications:
  email: false

env: # Environments
    - VERSION=1.1 VARIANT=debian
    - VERSION=1.2 VARIANT=debian
    - VERSION=1.3 VARIANT=debian
    - VERSION=1.4 VARIANT=debian
